export const Scales = [
  {
    steps: [0, 2, 4, 5, 7, 9, 11],
    alias_eng: 'Ionian',
    alias_pl: 'Jońska',
    value: 'ionian',
  },
  {
    steps: [0, 2, 3, 5, 7, 9, 10],
    alias_eng: 'Dorian',
    alias_pl: 'Dorycka',
    value: 'dorian',
  },
  {
    steps: [0, 1, 3, 5, 7, 8, 10],
    alias_eng: 'Phrygian',
    alias_pl: 'Frygijska',
    value: 'phrygian',
  },
  {
    steps: [0, 2, 4, 6, 7, 9, 11],
    alias_eng: 'Lydian',
    alias_pl: 'Lidyjska',
    value: 'lydian',
  },
  {
    steps: [0, 2, 4, 5, 7, 9, 10],
    alias_eng: 'Mixolydian',
    alias_pl: 'Miksolidyjska',
    value: 'mixolydian',
  },
  {
    steps: [0, 2, 3, 5, 7, 8, 10],
    alias_eng: 'Aeolian',
    alias_pl: 'Eolska',
    value: 'aeolian',
  },
  {
    steps: [0, 1, 3, 5, 6, 8, 10],
    alias_eng: 'Locrian',
    alias_pl: 'Lokrycka',
    value: 'locrian',
  },
  {
    steps: [0, 2, 3, 5, 7, 8, 11],
    alias_eng: 'Harmonic minor',
    alias_pl: 'Harmoniczna mol',
    value: 'harmonic_minor',
  },
  {
    steps: [0, 1, 3, 5, 6, 9, 10],
    alias_eng: 'Locrian 13 mode',
    alias_pl: 'Lokrycka 13',
    value: 'locrian_13',
  },
  {
    steps: [0, 2, 4, 5, 8, 9, 11],
    alias_eng: 'Ionian #5 mode',
    alias_pl: 'Jońska #5',
    value: 'ionian_#5',
  },
  {
    steps: [0, 2, 3, 6, 7, 9, 10],
    alias_eng: 'Dorian #11 mode',
    alias_pl: 'Dorycka #11',
    value: 'dorian_#11',
  },
  {
    steps: [0, 1, 4, 5, 7, 8, 10],
    alias_eng: 'Phrygian dominant',
    alias_pl: 'Frygijska dominantowa',
    valie: 'phrygian_dominant',
  },
  {
    steps: [0, 3, 4, 6, 7, 9, 11],
    alias_eng: 'Lydian #9 mode',
    alias_pl: 'Lidyjska #9',
    value: 'lydian_#9',
  },
  {
    steps: [0, 1, 3, 4, 6, 8, 9],
    alias_eng: 'Harmonic dimished',
    alias_pl: 'Harmoniczna zmniejszona',
    value: 'harmonic_dimished',
  },
  {
    steps: [0, 2, 3, 5, 7, 9, 11],
    alias_eng: 'Melodic minor',
    alias_pl: 'Melodyczna mol',
    value: 'melodic_minor',
  },
  {
    steps: [0, 1, 3, 5, 7, 9, 10],
    alias_eng: 'Dorian b9 mode',
    alias_pl: 'Dorycka b9',
    value: 'dorian_b9',
  },
  {
    steps: [0, 2, 4, 6, 8, 9, 11],
    alias_eng: 'Lydian augmented',
    alias_pl: 'Lidyjska zwiększona',
    valie: 'lydian_augmented',
  },
  {
    steps: [0, 2, 4, 6, 7, 9, 10],
    alias_eng: 'Lydian dominant',
    alias_pl: 'Lidyjska dominantowa',
    value: 'lydian_dominant',
  },
  {
    steps: [0, 2, 4, 5, 7, 8, 10],
    alias_eng: 'Mixolydian b13 mode',
    alias_pl: 'Mixolidyjska b13',
    value: 'mixolydian_b13',
  },
  {
    steps: [0, 2, 3, 5, 6, 8, 10],
    alias_eng: 'Locrian 9 mode',
    alias_pl: 'Lokrycka 9',
    value: 'locrian_9',
  },
  {
    steps: [0, 1, 3, 4, 6, 8, 10],
    alias_eng: 'Superlocrian',
    alias_pl: 'Superlokrycka',
    value: 'superlocrian',
  },
  {
    steps: [0, 2, 4, 5, 7, 8, 11],
    alias_eng: 'Harmonic major',
    alias_pl: 'Harmoniczna dur',
    value: 'harmonic_major',
  },
  {
    steps: [0, 2, 3, 5, 6, 9, 10],
    alias_eng: 'Dorian b5 mode',
    alias_pl: 'Dorycka b5',
    value: 'dorian_b5',
  },
  {
    steps: [0, 1, 3, 4, 7, 8, 10],
    alias_eng: 'Phrygian b11 mode',
    alias_pl: 'Frygijska b11',
    value: 'phrygian_b11',
  },
  {
    steps: [0, 2, 3, 6, 7, 9, 11],
    alias_eng: 'Lydian b3 mode',
    alias_pl: 'Lidyjska b3',
    value: 'lydian_b3',
  },
  {
    steps: [0, 1, 4, 5, 7, 9, 10],
    alias_eng: 'Mixolydian b9',
    alias_pl: 'Miksolidyjska',
    value: 'mixolydian_b9',
  },
  {
    steps: [0, 3, 4, 6, 8, 9, 11],
    alias_eng: 'Lydian augmented #9 mode',
    alias_pl: 'Lidyjska zwiększona #9',
    value: 'lydian_augmented_#9',
  },
  {
    steps: [0, 1, 3, 5, 6, 8, 9],
    alias_eng: 'Locrian bb7 mode',
    alias_pl: 'Lokrycka bb7',
    value: 'locrian_bb7',
  },
  {
    steps: [0, 1, 4, 5, 7, 8, 11],
    alias_eng: 'Double harmonic major',
    alias_pl: 'Podwójnie harmoniczna dur',
    value: 'double_harmonic_major',
  },
  {
    steps: [0, 3, 4, 6, 7, 10, 11],
    alias_eng: 'Lydian #2 #6 mode',
    alias_pl: 'Lidyjska #2 #6',
    value: 'lydian_#2_#6',
  },
  {
    steps: [0, 1, 3, 4, 7, 8, 9],
    alias_eng: 'Ultraphrygian',
    alias_pl: 'Ultrafrygijska',
    value: 'ultraphrygian',
  },
  {
    steps: [0, 2, 3, 6, 7, 8, 11],
    alias_eng: 'Double harmonic minor',
    alias_pl: 'Podwójnie harmoniczna mol',
    value: 'double_harmonic_minor',
  },
  {
    steps: [0, 1, 4, 5, 6, 9, 10],
    alias_eng: 'Oriental',
    alias_pl: 'Orientalna',
    value: 'oriental',
  },
  {
    steps: [0, 3, 4, 5, 8, 9, 11],
    alias_eng: 'Ionian augmented #2 mode',
    alias_pl: 'Jońska zwiększona #2',
    value: 'ionian_augmented_#2',
  },
  {
    steps: [0, 1, 2, 5, 6, 8, 9],
    alias_eng: 'Locrian bb3 bb7 mode',
    alias_pl: 'Lokrycka bb3 bb7',
    value: 'locrian_bb3_bb7',
  },
  {
    steps: [0, 2, 4, 7, 9],
    alias_eng: 'Pentatonic major',
    alias_pl: 'Pentatonika dur',
    value: 'pentatonic_major',
  },
  {
    steps: [0, 2, 5, 7, 10],
    alias_eng: 'Pentatonic suspended',
    alias_pl: 'Pentatonika sus',
    value: 'pentatonic_suspended: ',
  },
  {
    steps: [0, 3, 5, 8, 10],
    alias_eng: 'Pentatonic blues minor',
    alias_pl: 'Pentatonika blues mol',
    value: 'pentatonic_blues_minor',
  },
  {
    steps: [0, 2, 5, 7, 9],
    alias_eng: 'Pentatonic blues major',
    alias_pl: 'Pentatonika blues dur',
    value: 'pentatonic_blues_major',
  },
  {
    steps: [0, 3, 5, 7, 10],
    alias_eng: 'Pentatonic minor',
    alias_pl: 'Pentatonika mol',
    value: 'pentatonic_minor',
  },
  {
    steps: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    alias_eng: 'Chromatic',
    alias_pl: 'Chromatyczna',
    value: 'chromatic',
  },
  {
    steps: [0, 2, 4, 6, 8, 10],
    alias_eng: 'Wholetone',
    alias_pl: 'Całotonowa',
    value: 'wholetone',
  },
  {
    steps: [0, 3, 4, 7, 8, 11],
    alias_eng: 'Augmented',
    alias_pl: 'Zwiększona',
    value: 'augmented',
  },
  {
    steps: [0, 2, 3, 5, 6, 8, 9, 11],
    alias_eng: 'Dimished',
    alias_pl: 'Zmniejszona',
    value: 'dimished',
  },
  {
    steps: [0, 1, 3, 4, 6, 7, 9, 10],
    alias_eng: 'Dimished dominant',
    alias_pl: 'Zmniejszona dominantowa',
    value: 'dimished_dominant',
  },
  {
    steps: [0, 3, 6, 9],
    alias_eng: 'Minor thirds',
    alias_pl: 'Tercje małe',
    value: 'minor_thirds',
  },
  {
    steps: [0, 4, 8],
    alias_eng: 'Major thirds',
    alias_pl: 'Tercje duże',
    value: 'major_thirds',
  },
  {
    steps: [0, 2, 4, 5, 7, 9, 10, 11],
    alias_eng: 'Bebop Ionian',
    alias_pl: 'Bebop Jońska',
    value: 'bebop_ionian',
  },
  {
    steps: [0, 2, 3, 4, 5, 7, 9, 10],
    alias_eng: 'Bebop Dorian',
    alias_pl: 'Bebop Dorycka',
    value: 'bebop_dorian',
  },
  {
    steps: [0, 2, 3, 5, 7, 9, 10, 11],
    alias_eng: 'Bebop Dorian altered',
    alias_pl: 'Bebop Dorycka alterowana',
    value: 'bebop_dorian_altered',
  },
  {
    steps: [0, 2, 3, 5, 7, 8, 10, 11],
    alias_eng: 'Bebop Harmonic minor',
    alias_pl: 'Bebop Harmoniczna mol',
    value: 'bebop_harmonic_minor',
  },
  {
    steps: [0, 2, 3, 5, 7, 8, 9, 11],
    alias_eng: 'Bebop Melodic minor',
    alias_pl: 'Bebop Melodyczna mol',
    value: 'bebop_melodic_minor',
  },
  {
    steps: [0, 2, 4, 5, 7, 9, 10, 11],
    alias_eng: 'Bebop Dominant',
    alias_pl: 'Bebop Dominantowa',
    value: 'bebop_dominant',
  },
  {
    steps: [0, 3, 5, 6, 7, 10],
    alias_eng: 'Blues minor',
    alias_pl: 'Blues mol',
    value: 'blues_minor',
  },
  {
    steps: [0, 2, 3, 4, 7, 9],
    alias_eng: 'Blues major',
    alias_pl: 'Blues dur',
    value: 'blues_major',
  },
  {
    steps: [0, 2, 3, 4, 5, 6, 8, 9, 11],
    alias_eng: 'Mixoblues',
    alias_pl: 'Mixoblues',
    value: 'mixo_blues',
  },
  {
    steps: [0, 2, 4, 7, 10],
    alias_eng: 'Pentatonic dominant',
    alias_pl: 'Pentatonika dominantowa',
    value: 'pentatonic_dominant',
  },
];

export const TreeScales = [
  {
    key: '0',
    label: 'Ionian',
    data: 'Ionian Scale',
    icon: 'pi pi-fw pi-music',
    selectable: false,
    children: [
      { key: 'ionian', label: 'Ionian', data: 'Ionian', icon: 'pi pi-fw pi-music' },
      { key: 'dorian', label: 'Dorian', data: 'Dorian', icon: 'pi pi-fw pi-music' },
      { key: 'phrygian', label: 'Phrygian', data: 'Phrygian', icon: 'pi pi-fw pi-music' },
      { key: 'lydian', label: 'Lydian', data: 'Lydian', icon: 'pi pi-fw pi-music' },
      { key: 'mixolydian', label: 'Mixolydian', data: 'Mixolydian', icon: 'pi pi-fw pi-music' },
      { key: 'aeolian', label: 'Aeolian', data: 'Aeolian', icon: 'pi pi-fw pi-music' },
      { key: 'locrian', label: 'Locrian', data: 'Locrian', icon: 'pi pi-fw pi-music' },
    ],
  },
  {
    key: '1',
    label: 'Harmonic Minor',
    data: 'Harmonic Minor Scale',
    icon: 'pi pi-fw pi-music',
    selectable: false,
    children: [
      { key: 'harmonic_minor', label: 'Harmonic Minor', data: 'Harmonic Minor', icon: 'pi pi-fw pi-music' },
      { key: 'locrian_13', label: 'Locrian 13', data: 'Locrian 13', icon: 'pi pi-fw pi-music' },
      { key: 'ionian_#5', label: 'Ionian #5', data: 'Ionian #5', icon: 'pi pi-fw pi-music' },
      { key: 'dorian_#11', label: 'Dorian #11', data: 'Dorian #11', icon: 'pi pi-fw pi-music' },
      { key: 'phrygian_dominant', label: 'Phrygian Dominant', data: 'Phrygian Dominant', icon: 'pi pi-fw pi-music' },
      { key: 'lydian_#9', label: 'Lydian #9', data: 'Lydian #9', icon: 'pi pi-fw pi-music' },
      {
        key: 'harmonic_dimished',
        label: 'Harmonic Diminished',
        data: 'Harmonic Diminished',
        icon: 'pi pi-fw pi-music',
      },
    ],
  },
  {
    key: '2',
    label: 'Melodic Minor',
    data: 'Melodic Minor Scale',
    icon: 'pi pi-fw pi-music',
    selectable: false,
    children: [
      { key: 'melodic_minor', label: 'Melodic Minor', data: 'Melodic Minor', icon: 'pi pi-fw pi-music' },
      { key: 'dorian_b9', label: 'Dorian b9', data: 'Dorian b9', icon: 'pi pi-fw pi-music' },
      { key: 'lydian_augmented', label: 'Lydian Augmented', data: 'Lydian Augmented', icon: 'pi pi-fw pi-music' },
      { key: 'lydian_dominant', label: 'Lydian Dominant', data: 'Lydian Dominant', icon: 'pi pi-fw pi-music' },
      { key: 'mixolydian_b13', label: 'Mixolydian b13', data: 'Mixolydian b13', icon: 'pi pi-fw pi-music' },
      { key: 'locrian_9', label: 'Locrian 9', data: 'Locrian 9', icon: 'pi pi-fw pi-music' },
      { key: 'superlocrian', label: 'Superlocrian', data: 'Superlocrian', icon: 'pi pi-fw pi-music' },
    ],
  },
  {
    key: '3',
    label: 'Harmonic Major',
    data: 'Harmonic Major Scale',
    icon: 'pi pi-fw pi-music',
    selectable: false,
    children: [
      { key: 'harmonic_major', label: 'Harmonic Major', data: 'Harmonic Major', icon: 'pi pi-fw pi-music' },
      { key: 'dorian_b5', label: 'Dorian b5', data: 'Dorian b5', icon: 'pi pi-fw pi-music' },
      { key: 'phrygian_b11', label: 'Phrygian b11', data: 'Phrygian b11', icon: 'pi pi-fw pi-music' },
      { key: 'lydian_b3', label: 'Lydian b3', data: 'Lydian b3', icon: 'pi pi-fw pi-music' },
      { key: 'mixolydian_b9', label: 'Mixolydian b9', data: 'Mixolydian b9', icon: 'pi pi-fw pi-music' },
      {
        key: 'lydian_augmented_#9',
        label: 'Lydian Augmented #9',
        data: 'Lydian Augmented #9',
        icon: 'pi pi-fw pi-music',
      },
      { key: 'locrian_bb7', label: 'Locrian bb7', data: 'Locrian bb7', icon: 'pi pi-fw pi-music' },
    ],
  },
  {
    key: '4',
    label: 'Double Harmonic Major',
    data: 'Double Harmonic Major Scale',
    icon: 'pi pi-fw pi-music',
    selectable: false,
    children: [
      {
        key: 'double_harmonic_major',
        label: 'Double Harmonic Major',
        data: 'Double Harmonic Major',
        icon: 'pi pi-fw pi-music',
      },
      { key: 'lydian_#2_#6', label: 'Lydian #2 #6', data: 'Lydian #2 #6', icon: 'pi pi-fw pi-music' },
      { key: 'ultraphrygian', label: 'Ultraphrygian', data: 'Ultraphrygian', icon: 'pi pi-fw pi-music' },
      {
        key: 'double_harmonic_minor',
        label: 'Double Harmonic Minor',
        data: 'Double Harmonic Minor',
        icon: 'pi pi-fw pi-music',
      },
      { key: 'oriental', label: 'Oriental', data: 'Oriental', icon: 'pi pi-fw pi-music' },
      {
        key: 'ionian_augmented_#2',
        label: 'Ionian Augmented #2',
        data: 'Ionian Augmented #2',
        icon: 'pi pi-fw pi-music',
      },
      { key: 'locrian_bb3_bb7', label: 'Locrian bb3 bb7', data: 'Locrian bb3 bb7', icon: 'pi pi-fw pi-music' },
    ],
  },
  {
    key: '5',
    label: 'Pentatonic Major',
    data: 'Pentatonic Major Scale',
    icon: 'pi pi-fw pi-music',
    selectable: false,
    children: [
      { key: 'pentatonic_major', label: 'Pentatonic Major', data: 'Pentatonic Major', icon: 'pi pi-fw pi-music' },
      {
        key: 'pentatonic_suspended',
        label: 'Pentatonic Suspended',
        data: 'Pentatonic Suspended',
        icon: 'pi pi-fw pi-music',
      },
      {
        key: 'pentatonic_blues_minor',
        label: 'Pentatonic Blues Minor',
        data: 'Pentatonic Blues Minor',
        icon: 'pi pi-fw pi-music',
      },
      {
        key: 'pentatonic_blues_major',
        label: 'Pentatonic Blues Major',
        data: 'Pentatonic Blues Major',
        icon: 'pi pi-fw pi-music',
      },
      { key: 'pentatonic_minor', label: 'Pentatonic Minor', data: 'Pentatonic Minor', icon: 'pi pi-fw pi-music' },
    ],
  },
  {
    key: '6',
    label: 'Six Tone',
    data: 'Six Tone Scale',
    icon: 'pi pi-fw pi-music',
    selectable: false,
    children: [
      { key: 'wholetone', label: 'Whole Tone', data: 'Whole Tone', icon: 'pi pi-fw pi-music' },
      { key: 'augmented', label: 'Augmented', data: 'Augmented', icon: 'pi pi-fw pi-music' },
      { key: 'blues_minor', label: 'Blues Minor', data: 'Blues Minor', icon: 'pi pi-fw pi-music' },
      { key: 'blues_major', label: 'Blues Major', data: 'Blues Major', icon: 'pi pi-fw pi-music' },
    ],
  },
];

